package com.example.learnenglish.model;

public enum EnglishTenses {

    PAST_SIMPLE, PRESENT_SIMPLE, PRESENT_CONTINUOUS, FUTURE_SIMPLE, PAST_CONTINUOUS, PRESENT_PERFECT_CONTINUOUS,
    FUTURE_CONTINUOUS, PAST_PERFECT, PRESENT_PERFECT, FUTURE_PERFECT, PAST_PERFECT_CONTINUOUS, FUTURE_PERFECT_CONTINUOUS
}
